name: build-and-push-app
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/hostedtoolcache/CodeQL || true
          docker system prune -af || true
          docker builder prune -af || true
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          df -h
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push GPU app (uses gpu-stable base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            docker.io/jakeypoov/audio-scene-architect:gpu
            docker.io/jakeypoov/audio-scene-architect:gpu-${{ github.run_id }}
          build-args: |
            BASE_IMAGE=docker.io/jakeypoov/audio-scene-architect:gpu-stable
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
