name: Build GPU Base (rare)
on:
  workflow_dispatch:
  push:
    paths:
      - backend/requirements.txt
      - backend/requirements-heavy.txt
      - Dockerfile.gpu.base
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { username: ${{ secrets.DOCKERHUB_USERNAME }}, password: ${{ secrets.DOCKERHUB_TOKEN }} }
      - name: Build & push base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.gpu.base
          push: true
          tags: |
            jakeypoov/audio-scene-architect:gpu-base
          cache-from: type=registry,ref=jakeypoov/audio-scene-architect:buildcache-base
          cache-to: type=registry,ref=jakeypoov/audio-scene-architect:buildcache-base,mode=max
          platforms: linux/amd64
          provenance: false

