name: Build and Push GPU/CPU Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/audio-scene-architect
  TORCH_VERSION: ${{ vars.TORCH_VERSION || '2.3.1' }}
  TORCHAUDIO_VERSION: ${{ vars.TORCHAUDIO_VERSION || '2.3.1' }}
  AUDIOCRAFT_REF: ${{ vars.AUDIOCRAFT_REF || 'main' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compute tags
        id: tag
        run: |
          TS=$(date -u +%Y%m%d-%H%M%S)
          SHA7=${GITHUB_SHA::7}
          echo "stamp=${TS}-${SHA7}" >> $GITHUB_OUTPUT

      - name: Build GPU base image (optional cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gpu-base
          push: true
          tags: |
            docker.io/${{ env.IMAGE_REPO }}-gpu-base:${{ env.TORCH_VERSION }}-${{ env.AUDIOCRAFT_REF }}
          build-args: |
            TORCH_VERSION=${{ env.TORCH_VERSION }}
            TORCHAUDIO_VERSION=${{ env.TORCHAUDIO_VERSION }}
            AUDIOCRAFT_REF=${{ env.AUDIOCRAFT_REF }}
          cache-from: type=registry,ref=docker.io/${{ env.IMAGE_REPO }}-gpu-base:${{ env.TORCH_VERSION }}-${{ env.AUDIOCRAFT_REF }}
          cache-to: type=inline

      - name: Build and push GPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            docker.io/${{ env.IMAGE_REPO }}:gpu-${{ steps.tag.outputs.stamp }}
            docker.io/${{ env.IMAGE_REPO }}:gpu
          build-args: |
            BASE_IMAGE=docker.io/${{ env.IMAGE_REPO }}-gpu-base:${{ env.TORCH_VERSION }}-${{ env.AUDIOCRAFT_REF }}
          cache-from: type=registry,ref=docker.io/${{ env.IMAGE_REPO }}:gpu
          cache-to: type=inline

      - name: Build and push CPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: |
            docker.io/${{ env.IMAGE_REPO }}:cpu
          build-args: |
            BUILD_TAG=${{ steps.tag.outputs.stamp }}
          cache-to: type=inline

      - name: Smoke test container (CPU)
        run: |
          docker run -d --name asa-cpu -p 8000:8000 docker.io/${{ env.IMAGE_REPO }}:cpu
          chmod +x scripts/wait-ready.sh || true
          for i in {1..60}; do
            if curl -fsS "http://localhost:8000/api/ready" >/dev/null; then
              echo "Ready"
              break
            fi
            sleep 2
          done
          curl -fsS "http://localhost:8000/api/ready"
          bash scripts/acceptance.sh || (docker logs asa-cpu; exit 1)
          docker rm -f asa-cpu
