name: build-gpu-base
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - Dockerfile.gpu-base
      - docker/constraints-cu124.txt
      - .github/workflows/build-gpu-base.yml
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tags
        id: t
        run: |
          TS=$(date -u +'%Y%m%d-%H%M%S')
          echo "TAG=gpu-base-${TS}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build & push GPU base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gpu-base
          push: true
          tags: docker.io/jakeypoov/audio-scene-architect:${{ steps.t.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
      - name: Promote gpu-stable
        run: |
          docker buildx imagetools create \
            -t docker.io/jakeypoov/audio-scene-architect:gpu-stable \
            docker.io/jakeypoov/audio-scene-architect:${{ steps.t.outputs.TAG }}
      - name: Verify gpu-stable
        run: docker buildx imagetools inspect docker.io/jakeypoov/audio-scene-architect:gpu-stable
